=== nobletk/WebTech/Assignments/Bibliography/bibliography.dtd
<!ELEMENT bibliography (lists)>
<!ELEMENT lists (list+)>
<!ELEMENT list (author, title, ed,publisher, year, isbn,url)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT ed (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT url (link)>
<!ELEMENT link (#PCDATA)>

=== nobletk/WebTech/Assignments/Bibliography/bibliography.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliography SYSTEM "bibliography.dtd">
<?xml-stylesheet type="text/css" href="bibliography.css"?>


<bibliography>
   <lists>
        <list>
            <author>Eric A. Meyer,Estelle Weyl</author>
            <title>CSS:The Definitive Guide</title>
            <ed>4th ed</ed>
            <publisher>Oâ€™Reilly Media</publisher>
            <year>2017</year>
            <isbn>9781449393199</isbn>
            <url> <link> -</link></url>
        </list>
        <list>
            <author>Ben Frain</author>
            <title>Responsive Web Design with HTML5 and CSS</title>
            <ed>3rd ed</ed>
            <publisher>Pack Publishing</publisher>
            <year>2020</year>
            <isbn>9781839211560</isbn>
            <url> <link>https://www.packtpub.com/product/responsive-web-design-with-html5-and-css-third-edition/9781839211560 </link></url>
        </list>
        <list>
            <author>Amit Garg</author>
            <title>Junior Level Books
                Introduction to Computer</title>
            <ed></ed>
            <publisher>Reader's Zone</publisher>
            <year>2011</year>
            <isbn>9789350195611</isbn>
            <url> <link> -</link></url>
        </list>
        <list>
            <author>Sharad Kumar Verma</author>
            <title>Data Structure Using C</title>
            <ed></ed>
            <publisher>Thakur Publications Lucknow</publisher>
            <year>2015</year>
            <isbn>9789351633891</isbn>
            <url> <link> -</link></url>
        </list>
        <list>
            <author>Sharad Kumar Verma</author>
            <title>Client Server Computing</title>
            <ed></ed>
            <publisher> Sun India Publications, New Delhi</publisher>
            <year>2012</year>
            <isbn>9789380674322</isbn>
            <url> <link> -</link></url>
        </list>
        <list>
            <author>Lalit Kumar</author>
            <title>Client Server</title>
            <ed></ed>
            <publisher> Sun India Publications, New Delhi</publisher>
            <year>2012</year>
            <isbn>9789380674335</isbn>
            <url> <link> -</link></url>
        </list>
    </lists> 
</bibliography>

=== nobletk/WebTech/bibliography.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliography SYSTEM "bibliography.dtd">
<?xml-stylesheet type="text/css" href="bibliography.css"?>


<bibliography>
    <list>
        <author>Eric A. Meyer,Estelle Weyl</author>
        <title>CSS:The Definitive Guide</title>
        <publisher>Oâ€™Reilly Media</publisher>
        <year>2017</year>
        <isbn>9781449393199</isbn>
        <url xlink:href="https://www.packtpub.com/product/responsive-web-design-with-html5-and-css-third-edition/9781839211560%C2%A0"> 
            
        </url>
    </list>
</bibliography>
